using System;
using System.IO;
using System.Text;
using UnityEngine;
namespace Keshiya.Editor {
 public static class BalanceChecks {
  static int count;static StringBuilder log,metrics;static SkillCatalog skills;static ProgressionConfig progression;
  static void Check(bool ok,string name){count++;log.AppendLine((ok?"PASS: ":"FAIL: ")+name);if(!ok)throw new Exception("BALANCE FAIL: "+name);}
  static PerformanceModifiers Mod(int level){var p=new PlayerProgress(skills,progression);p.DebugPreset(level);var m=new PerformanceModifiers();p.Apply(m);return m;}
  public static void Run(){count=0;log=new StringBuilder();metrics=new StringBuilder();skills=Resources.Load<SkillCatalog>("SkillCatalog");progression=Resources.Load<ProgressionConfig>("ProgressionConfig");var t=Resources.Load<ToolCatalog>("ToolCatalog").tools;var c=Resources.Load<PrototypeConfig>("PrototypeConfig");var letter=Resources.Load<JobDefinition>("PrecisionJob");var z=Mod(0);var f=Mod(5);var ten=Mod(10);
   Check(Mathf.Approximately(z.erasePower,.9f)&&Mathf.Approximately(f.erasePower,1.4f)&&Mathf.Approximately(ten.erasePower,1.85f),"Efficiency milestones 0.90 / 1.40 / 1.85");Check(ten.erasePower/z.erasePower>2&&f.erasePower/z.erasePower>1.5f,"Mid and max gains distinctly exceed previous curve");Check(t[0].Power(ten)<t[2].Power(z)*.7f,"Sand retains a clear speed advantage over max ordinary");
   float[] removal=new float[3];int k=0;foreach(var m in new[]{z,f,ten}){using(var p=new Paper(c,.1f,letter)){p.Stroke(new Vector2(.14f,-.38f),new Vector2(.14f,.38f),3,1,t[0],m);removal[k]=p.Drawing.Erased;}metrics.AppendLine($"Lv{(k==0?0:k==1?5:10)} fixed stroke erased={removal[k]*100:0.000}%");k++;}
   Check(removal[1]>removal[0]*1.4f&&removal[2]>removal[1]*1.2f,"Actual identical stroke has separated Lv0/5/10 removal");
   using(var p=new Paper(c,.1f,letter)){var state=new EraserState();for(int pass=0;pass<65&&p.Drawing.Erased<.95f;pass++)foreach(var path in LetterLayout.Target)for(int i=1;i<path.Length;i++){p.Stroke(path[i-1],path[i],3,pass,t[0],z,t[0].Contact(z,ContactMode.Corner,state,0));state.Use(Vector2.Distance(path[i-1],path[i]),ContactMode.Corner,t[0],z);}var job=new Job(c,letter);job.StartWork();job.Tick(100000);Check(job.Complete(p)&&p.Protection.Loss==0&&job.Result.speed==0&&job.Result.basic==letter.baseReward,"Lv0 completes precision work safely without a time penalty");}
   var oldTen=Mod(10);oldTen.paperDamage=.6f;float newDamage,oldDamage;
   using(var a=new Paper(c))using(var b=new Paper(c)){a.Stroke(new Vector2(-.3f,0),new Vector2(.3f,0),24,1,t[0],ten);b.Stroke(new Vector2(-.3f,0),new Vector2(.3f,0),24,1,t[0],oldTen);newDamage=a.AverageDamage;oldDamage=b.AverageDamage;Check(newDamage>0&&newDamage<oldDamage*.8f,"Ordinary max paper protection is stronger but finite");metrics.AppendLine($"Ordinary paper damage at 24u/s: old={oldDamage:R} new={newDamage:R}");}
   Check(Mathf.Abs(t[2].DamageMultiplier(ten)-3)<.0001f,"Sand max damage multiplier remains exactly 3.0");using(var paper=new Paper(c)){for(int i=0;i<6;i++)paper.Stroke(new Vector2(-.3f,0),new Vector2(.3f,0),35,i*.05f,t[2],ten);Check(paper.PeakDamage>.1f,"Rough repeated sand use still damages paper at max skills");}
   using(var paper=new Paper(c)){for(int i=0;i<25;i++)paper.Stroke(new Vector2(-.3f,0),new Vector2(.3f,0),35,i*.05f,t[0],ten);Check(paper.PeakDamage>.1f,"Extreme focused ordinary rubbing is still dangerous at Lv10");}
   var oldConfig=UnityEngine.Object.Instantiate(c);oldConfig.protectedGlanceExponent=1;float oldLoss,newLoss;var oldInk=new PerformanceModifiers{protectedGlance=.5f};var newInk=new PerformanceModifiers{protectedGlance=.3f};
   using(var a=new Paper(oldConfig,.1f,letter))using(var b=new Paper(c,.1f,letter)){a.Stroke(new Vector2(.2f,-.4f),new Vector2(.2f,.4f),4,1,t[0],oldInk);b.Stroke(new Vector2(.2f,-.4f),new Vector2(.2f,.4f),4,1,t[0],newInk);oldLoss=a.Protection.Loss;newLoss=b.Protection.Loss;Check(newLoss>0&&newLoss<oldLoss*.85f,"Glancing ink contact receives stronger bounded relief");metrics.AppendLine($"Isolated Lv10 ink skill: old loss={oldLoss:R} new loss={newLoss:R}");}
   using(var p=new Paper(c,.1f,letter)){for(int i=0;i<40;i++)p.Stroke(new Vector2(-.25f,-.4f),new Vector2(-.25f,.4f),4,i,t[0],ten);Check(p.Protection.Loss>.2f,"Repeated direct protected-letter rubbing still causes major damage");}UnityEngine.Object.DestroyImmediate(oldConfig);
   float[] sharp=new float[3];k=0;foreach(var m in new[]{z,f,ten}){var state=new EraserState();state.Use(20,ContactMode.Corner,t[0],m);sharp[k++]=state.CornerSharpness;}
   Check(sharp[0]<.6f&&sharp[1]>sharp[0]+.1f&&sharp[2]>sharp[1]+.1f&&sharp[2]<1,"Corner loss is visible and CornerCare has finite tier differences");metrics.AppendLine($"Ordinary corner after 20u: {sharp[0]:0.000} / {sharp[1]:0.000} / {sharp[2]:0.000}");
   var faceState=new EraserState();var edgeState=new EraserState();faceState.Use(20,ContactMode.Face,t[0],z);edgeState.Use(20,ContactMode.Edge,t[0],z);Check(faceState.CornerSharpness==1&&edgeState.CornerSharpness<1&&edgeState.CornerSharpness>sharp[0],"Face preserves corners and edge wears them only lightly");
   var worn=new EraserState();worn.Use(20,ContactMode.Corner,t[0],z);Check(t[0].Contact(z,ContactMode.Corner,worn,0).HalfSize.x>t[0].Contact(z,ContactMode.Corner,new EraserState(),0).HalfSize.x,"Corner wear affects actual precision footprint");
   var sense=skills.Find(SkillKind.Sense);Check(sense.Effect(1)==.9f&&sense.Effect(5)==.78f&&sense.Effect(10)==.6f,"Sensing starts at 90 / 78 / 60 percent");Check(sense.Duration(10)==6.5f&&sense.Duration(5)==4.5f&&sense.Effect(0)>1,"Sensing duration improved, Lv0 remains unlearned");
   using(var paper=new Paper(c)){int pixel=Array.FindIndex(paper.Drawing.Ink,x=>x==0);paper.Drawing.Ink[pixel]=.003f;paper.Refresh();var before=paper.Texture.GetPixel(pixel%paper.Width,pixel/paper.Width);paper.Reveal(.4f);var after=paper.Texture.GetPixel(pixel%paper.Width,pixel/paper.Width);Check(before!=after&&paper.Drawing.Ink[pixel]==.003f,"Sensing catches faint graphite without erasing it");}
   float[] oldWear={.12f,.15f,.08f,.14f,.32f,.10f,.60f};for(int i=0;i<oldWear.Length;i++){var state=new EraserState{allowExhaustion=true};state.Use(50,ContactMode.Face,t[i],z);Check(state.UsedUnits>50*oldWear[i]&&state.Remaining(t[i],z)>0,"Noticeable finite body wear: "+t[i].id);metrics.AppendLine($"{t[i].id} remaining after 50u={state.Remaining(t[i],z)*100:0.00}%");}
   Check(t[5].price==7800&&t[5].price>=2600*3,"Premium requires substantially more savings");Check(t[5].erasePower>1.22f&&t[5].paperDamageMultiplier<.2f&&t[5].cornerWearRate<.002f&&t[5].protectedInkAbrasion<.3f,"Premium gets power, safety and durable-corner improvements");Check(t[5].Contact(z,ContactMode.Corner,new EraserState(),0).HalfSize.x<.023f,"Premium precision footprint is slightly narrower");Check(t[5].Contact(z).HalfSize.y<t[0].Contact(z).HalfSize.y&&t[5].crumbAmount<t[0].crumbAmount&&t[5].crumbAmount<t[6].crumbAmount,"Premium retains small face and weak byproduct income");
   using(var a=new Paper(c))using(var b=new Paper(c))using(var d=new Paper(c)){var from=new Vector2(-2,0);var to=new Vector2(2,0);a.Stroke(from,to,4,1,t[0],z);b.Stroke(from,to,4,1,t[5],z);d.Stroke(from,to,4,1,t[4],z);Check(b.Drawing.Erased<a.Drawing.Erased&&a.Drawing.Erased<d.Drawing.Erased,"Premium remains worse on broad work than ordinary and large");}
   Check(t[6].price==0&&t[6].longCrumbPotential==.60f&&t[1].longCrumbPotential==1.75f,"Free piece weakened; paid soft long-growth retained");Check(t[4].radius==.5f&&t[0].radius==.27f&&t[0].erasePower==1.15f&&t[2].erasePower==3.6f,"Ordinary, large and sand base roles retained");
   var exp=new PlayerProgress(skills,progression);exp.Gain(CraftBranch.Erasing,80,"鉛筆を消した量");exp.Gain(CraftBranch.Precision,15,"紙ダメージなしで完了");exp.Gain(CraftBranch.Crumbs,23,"長い一本を回収");var lines=exp.ExperienceLines();Check(exp.banks[0].earnedSP==1&&exp.Next(CraftBranch.Erasing)==95&&exp.banks[1].earnedSP==0,"EXP to SP pace unchanged");for(int i=0;i<3;i++){float sum=0;foreach(var reason in exp.reasons)if((int)reason.branch==i)sum+=reason.amount;Check(Mathf.Approximately(sum,exp.jobExp[i])&&lines.Exists(x=>x.StartsWith(SkillCatalog.BranchName((CraftBranch)i))),"Grouped EXP totals and reasons agree: "+i);}float total=exp.banks[0].total;exp.ExperienceLines();Check(exp.banks[0].total==total,"Reading breakdown cannot award experience");
   var debug=new EraserState{allowExhaustion=true};debug.DebugSharpness(.5f);debug.DebugRemaining(.2f,t[0],ten);Check(Mathf.Abs(debug.Remaining(t[0],ten)-.2f)<.0001f&&debug.CornerSharpness==.5f,"Debug remaining does not reset sharpness");float used=debug.UsedUnits;debug.DebugSharpness(.1f);Check(debug.UsedUnits==used&&debug.CornerSharpness==.1f,"Debug sharpness does not refill body");debug.Use(1,ContactMode.Corner,t[0],ten);Check(debug.CornerSharpness<=.1f,"Using a worn debug corner never sharpens it");
   var inventory=new ToolInventory();inventory.Initialize(Resources.Load<ToolCatalog>("ToolCatalog"));var wallet=new Wallet();wallet.DebugCredit(7799);Check(!inventory.Purchase(t[5],wallet,out _),"Premium price is enforced");wallet.DebugCredit(8001);Check(inventory.Purchase(t[5],wallet,out var one)&&inventory.Purchase(t[5],wallet,out var two)&&one.instanceId!=two.instanceId,"Saving purchases two independent premium copies");
   Check(f.radius==1.075f&&ten.radius==1.15f&&ten.wear==.65f&&ten.longGrowth==1.25f&&ten.crumbAmount==1.3f&&ten.ballYield==1.2f,"Non-target skill endpoints preserved");
   var presetItem=new OwnedEraser();presetItem.state.DebugRemaining(.5f,t[0],z);Check(presetItem.Condition!="新品","Body preset updates condition without requiring artificial travel");presetItem.state.DebugSharpness(.1f);Check(presetItem.Condition=="角が丸い","Corner preset updates individual condition");
   Directory.CreateDirectory("TestResults");File.WriteAllText("TestResults/balance-checks.txt",$"PASS {count} balance checks\n"+log);File.WriteAllText("TestResults/balance-measurements.txt",metrics.ToString());Debug.Log($"BALANCE_CHECKS_OK {count}");
  }
 }
}
