using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
namespace Keshiya.Editor {
 public static class FoundationChecks {
  static int count;static readonly List<string> lines=new List<string>();
  static void Check(bool ok,string name){count++;lines.Add((ok?"PASS ":"FAIL ")+name);File.WriteAllLines("TestResults-Foundation/editor.txt",lines);if(!ok)throw new Exception(name);}
  static void Reject(Action action,string name){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,name);}
  public static void Run(){Directory.CreateDirectory("TestResults-Foundation");count=0;lines.Clear();JobContentPipeline.Import();JobContentPipeline.ValidateAll();EditorSceneManager.OpenScene("Assets/Keshiya/Scenes/Prototype.unity");var game=UnityEngine.Object.FindFirstObjectByType<PrototypeGame>();var specs=JobContentPipeline.Definitions();var registry=Resources.Load<JobRegistry>("JobRegistry");
   Check(specs.Length==9,"Eight frozen definitions and one DEV definition");Check(registry.Merge(game.Jobs).Length==28,"Registry retains existing order and count");Check(registry.Merge(game.Jobs).SequenceEqual(game.Jobs),"Registry preserves exact scene order");Check(!registry.released.Any(j=>j.content.developmentOnly),"DEV excluded from runtime registry");
   foreach(var s in specs){var j=AssetDatabase.LoadAssetAtPath<JobDefinition>(s.runtimeAsset);Check(j!=null&&j.artwork.Valid,s.id+" imported existing JobDefinition");Check(j.clientQuote==s.clientLetter,s.id+" exact letter");Check(j.thankYou==s.completionMessage,s.id+" exact completion");Check(j.instruction==s.workInstruction,s.id+" exact instruction");Check(TextCatalog.Require(j.content.titleTextId)==j.displayName,s.id+" title resolves");Check(j.baseReward==s.baseReward&&j.requiredErasure==s.requiredErasure,s.id+" balance unchanged");}
   var manga=specs.First(s=>s.id=="TEST_003");Check(manga.completionMessage.EndsWith("おやすみなさう。")&&manga.clientLetter.Contains("おnがい"),"Intentional manga typos");Reject(()=>TextCatalog.Require("MISSING_TEST_ID"),"Missing text rejected");Reject(()=>TextCatalog.Parse("{\"entries\":[{\"id\":\"X\",\"value\":\"a\"},{\"id\":\"X\",\"value\":\"b\"}]}"),"Duplicate text rejected");
   Check(typeof(TutorialHints).TypeInitializer==null,"Tutorial construction does not load Unity resources from a static initializer");
   var originalTutorial=System.Text.RegularExpressions.Regex.Matches(File.ReadAllText("Tools/JobPipeline/tutorial-baseline.json"),"\"([^\"]*)\"").Cast<System.Text.RegularExpressions.Match>().Select(m=>m.Groups[1].Value).ToArray();Check(TutorialHints.Steps.SequenceEqual(originalTutorial),"Tutorial byte-equivalent Japanese strings");
   var dev=AssetDatabase.LoadAssetAtPath<JobDefinition>(specs.First(s=>s.visibility=="development").runtimeAsset);Check(AssetDatabase.GetAssetPath(dev).Contains("/Editor/"),"DEV asset is Editor-only");
   var missingPaper=dev.artwork.paper;try{dev.artwork.paper=null;Check(JobContentPipeline.Validate().Any(message=>message.Contains(dev.id+" missing runtime texture Paper")),"Validator reports missing runtime Paper without null exception");}finally{dev.artwork.paper=missingPaper;}
   for(int layer=0;layer<7;layer++){var p=JobPreviewWindow.Compose(dev.artwork,layer,0,false,false,out var stats);Check(p.width==1240&&p.height==1754&&stats.Contains("Overlap"),"Preview layer "+layer);UnityEngine.Object.DestroyImmediate(p);}
   foreach(float fraction in new[]{.5f,.95f,1f}){var t=JobPreviewWindow.Compose(dev.artwork,0,fraction,true,true,out var stats);Check(t!=null&&stats.Contains("Erase"),"Preview state and overlays "+fraction);UnityEngine.Object.DestroyImmediate(t);}
   using(var paper=new Paper(game.Config,game.Feel.erasureGrain,dev)){var tool=game.Catalog.tools[0];var state=new EraserState();var skills=new PerformanceModifiers();var fp=tool.Contact(skills,ContactMode.Corner,state,0);int xmin=paper.Width,xmax=0,ymin=paper.Height,ymax=0;for(int y=0;y<paper.Height;y++)for(int x=0;x<paper.Width;x++)if(paper.Drawing.Ink[y*paper.Width+x]>0){xmin=Math.Min(xmin,x);xmax=Math.Max(xmax,x);ymin=Math.Min(ymin,y);ymax=Math.Max(ymax,y);}
    float left=((xmin+.5f)/paper.Width-.5f)*paper.Size.x-.025f,right=((xmax+.5f)/paper.Width-.5f)*paper.Size.x+.025f,bottom=((ymin+.5f)/paper.Height-.5f)*paper.Size.y,top=((ymax+.5f)/paper.Height-.5f)*paper.Size.y;
    for(int pass=0;pass<100&&paper.Drawing.Erased<.95f;pass++)for(float y=bottom;y<=top+.015f;y+=.025f)paper.Stroke(new Vector2(left,y)-fp.Offset,new Vector2(right,y)-fp.Offset,2,pass*2,tool,skills,fp,state);
    Check(paper.Drawing.Erased>=.95f,"DEV pipeline true stroke 95% completion");Check(paper.Protection.Loss<.01f,"DEV protects recipient");
   }
   SaveChecks(game);
   Check(DevelopmentMetrics.Available,"Editor metrics compiled");DevelopmentMetrics.Enabled=false;Check(DevelopmentMetrics.Measure("disabled")==null,"Metrics off by default has no scope");DevelopmentMetrics.Enabled=true;using(DevelopmentMetrics.Measure("check")){}Check(DevelopmentMetrics.Samples.Count>0,"Metrics timing recorded");DevelopmentMetrics.Texture(dev.artwork.paper);Check(DevelopmentMetrics.Samples.Any(s=>s.textureBytes>0),"Texture memory measured");DevelopmentMetrics.Enabled=false;
   lines.Add("Checks="+count+"; Failures=0");File.WriteAllLines("TestResults-Foundation/editor.txt",lines);Debug.Log("FOUNDATION_CHECKS_OK "+count);
  }
  static void SaveChecks(PrototypeGame game){var p=new PlayerProgress(Resources.Load<SkillCatalog>("SkillCatalog"),Resources.Load<ProgressionConfig>("ProgressionConfig"));p.tools.Initialize(game.Catalog);var e=new CrumbEconomy(game.EconomyConfig,p.wallet){Progress=p};p.wallet.DebugCredit(12345);p.tools.Selected.state.DebugSharpness(.4f);p.banks[0].total=12;p.banks[0].remainder=12;
   var save=SaveStore.Capture(p,e);var restored=SaveStore.Decode(JsonUtility.ToJson(save));Check(restored.SaveVersion==2,"Save version2");var p2=new PlayerProgress(Resources.Load<SkillCatalog>("SkillCatalog"),Resources.Load<ProgressionConfig>("ProgressionConfig"));p2.ImportSave(restored.progress);var e2=new CrumbEconomy(game.EconomyConfig,p2.wallet);e2.ImportSave(restored.economy);
   Check(p2.wallet.Balance==12345,"Wallet roundtrip");Check(p2.tools.items.Count==3&&p2.tools.Selected.state.CornerSharpness==.4f,"Individual state roundtrip");Check(p2.banks[0].total==12,"EXP roundtrip");Check(e2.JobId==e.JobId&&e2.AccountedMass==e.AccountedMass,"Economy ledger roundtrip");
   var walletRef=p2.wallet;var toolsRef=p2.tools;p2.ImportSave(restored.progress);Check(ReferenceEquals(walletRef,p2.wallet)&&ReferenceEquals(e2.Wallet,p2.wallet)&&ReferenceEquals(toolsRef,p2.tools),"Live wallet and inventory references remain connected");
   p2.tools.Selected.state.special.graphiteLoad=.8f;p2.tools.Selected.state.special.toastLevel=.3f;
   ZigzagTestPath.Trace(e2,game.Catalog.tools[1]);e2.Collect();e2.Roll();Check(e2.Inventory.Count>0&&e2.Ball.Grams>0,"Save fixture contains earned strands and ball");
   var rich=SaveStore.Decode(JsonUtility.ToJson(SaveStore.Capture(p2,e2)));float mass=e2.AccountedMass;long price=e2.InventoryPrice;p2.ImportSave(rich.progress);e2.ImportSave(rich.economy);
   Check(Mathf.Abs(e2.AccountedMass-mass)<.0001f&&e2.InventoryPrice==price,"Strand value and mass survive roundtrip");Check(p2.tools.Selected.state.special.graphiteLoad==.8f&&p2.tools.Selected.state.special.toastLevel==.3f,"Independent special states survive save");
   long strand=e2.Inventory[0].Id,earned=e2.SellPiece(strand);Check(earned>0&&p2.wallet.CrumbIncome==earned,"Restored sale uses live wallet");Check(e2.SellPiece(strand)==0,"Restored inventory cannot sell twice");
   p2.wallet.CreditJob(e2.JobId,500);var paid=SaveStore.Capture(p2,e2);p2.ImportSave(paid.progress);Check(!p2.wallet.CreditJob(e2.JobId,500),"Reward deduplication survives save");
   p2.work.Choose(0,1);p2.work.Begin();p2.work.Finish(e2.JobId,game.Jobs[0],new RewardResult{erased=1,seconds=30});p2.work.ShowBoard();var history=SaveStore.Capture(p2,e2);p2.ImportSave(history.progress);Check(p2.work.CompletedCount==1&&p2.work.Record(game.Jobs[0].id)!=null,"Job history roundtrip");
   var legacy=new LegacySessionExport{progress=save.progress,economy=save.economy};var migrated=SaveStore.Decode(JsonUtility.ToJson(legacy));Check(migrated.SaveVersion==2&&migrated.storyFlags.Length==0,"Explicit ET01 session export migration");
   string folder=Path.Combine("TestResults-Foundation","SaveSandbox-"+Guid.NewGuid().ToString("N"));Check(SaveStore.Load(folder).status=="new-game","New save slot");SaveStore.Save(folder,save);Check(SaveStore.Load(folder).data!=null,"Save/load");p.wallet.DebugCredit(100);SaveStore.Save(folder,SaveStore.Capture(p,e));Check(File.Exists(Path.Combine(folder,"progress.json.bak")),"Previous valid backup");Check(SaveStore.Load(folder).data.progress.playerJson.Contains("12445"),"Overwrite save");
   string primary=Path.Combine(folder,"progress.json");File.WriteAllText(primary,"truncated");var recovered=SaveStore.Load(folder);Check(recovered.fromBackup&&recovered.data!=null,"Corrupt primary recovers backup");Reject(()=>SaveStore.Save(folder,save),"Corrupt primary cannot destroy good backup");SaveStore.RecoverBackup(folder);Check(!SaveStore.Load(folder).fromBackup,"Explicit backup repair");
   string before=File.ReadAllText(primary);SaveStore.SaveSettings(folder,new UserSettings{contactGuide=false,volume=.5f});Check(File.ReadAllText(primary)==before,"Settings do not alter progress");Check(!SaveStore.LoadSettings(folder).contactGuide&&SaveStore.LoadSettings(folder).volume==.5f,"Settings roundtrip");SaveStore.SaveSettings(folder,new UserSettings{volume=.2f});File.WriteAllText(Path.Combine(folder,"settings.json"),"broken");Check(SaveStore.LoadSettings(folder).volume==.5f,"Settings backup recovery");
   File.WriteAllText(primary,"broken");File.WriteAllText(primary+".bak","broken");Check(SaveStore.Load(folder).RequiresReset,"Double corruption requests reset without overwrite");Reject(()=>SaveStore.Decode("{\"SaveVersion\":99}"),"Future version rejected");Reject(()=>SaveStore.Decode("{\"SaveVersion\":2}"),"Missing progress rejected");p.work.Choose(0,1);p.work.Begin();Reject(()=>SaveStore.Capture(p,e),"Mid-work save not silently truncated");
  }
 }
}
