using UnityEngine;
using UnityEditor;
namespace Keshiya.Editor {
 public static class Prototype06Setup {
  static T Asset<T>(string name,out bool fresh) where T:ScriptableObject {string path="Assets/Keshiya/Resources/"+name+".asset";var a=AssetDatabase.LoadAssetAtPath<T>(path);fresh=a==null;if(fresh){a=ScriptableObject.CreateInstance<T>();AssetDatabase.CreateAsset(a,path);}return a;}
  static EraserContactProfile Profile(string name,Vector2 size){var p=Asset<EraserContactProfile>(name,out var fresh);if(fresh){p.halfSizeMultiplier=size;EditorUtility.SetDirty(p);}return p;}
  public static void Apply(PrototypeGame game){
   string[] ids={"ordinary","soft","sand"},shorts={"普通","やわらか","砂消し"},descs={"迷った日の一本。広さと安全性の釣り合いがよい、仕事の基準です。","薄い紙にも、長い消しカスにも。よくまとまりますが、消去には少し手数が必要です。","速く消える、紙も削れる。手早く済ませたい時ほど、手加減を。"};int[] prices={160,280,650};
   for(int i=0;i<3;i++){var d=game.Catalog.tools[i];if(string.IsNullOrEmpty(d.id)){d.id=ids[i];d.shortName=shorts[i];d.description=descs[i];d.price=prices[i];EditorUtility.SetDirty(d);}}
   var thin=Asset<EraserDefinition>("DraftingEraser",out var fresh);
   if(fresh){thin.id="drafting";thin.displayName="細型製図消し";thin.shortName="細型";thin.price=1050;thin.description="狭いところへ届く細身の一本。尖った角は便利ですが、広い紙では手数がかかります。";thin.role="細部修正 / 広範囲は苦手";thin.erasePower=1.05f;thin.paperDamageMultiplier=.65f;thin.protectedInkAbrasion=.6f;thin.radius=.21f;thin.wearRate=.14f;thin.cornerWearRate=.013f;thin.cornerSpread=1.2f;thin.crumbAmount=.75f;thin.longCrumbPotential=.8f;thin.crumbCohesion=.45f;thin.iconScale=new Vector2(.92f,.40f);thin.labelColor=new Color(.29f,.48f,.63f);thin.contactProfile=Profile("DraftingFace",new Vector2(1,.32f));thin.edgeProfile=Profile("DraftingEdge",new Vector2(1,.11f));thin.cornerProfile=Profile("DraftingCorner",new Vector2(.105f,.105f));EditorUtility.SetDirty(thin);}
   var large=Asset<EraserDefinition>("LargeEraser",out fresh);
   if(fresh){large.id="large";large.displayName="大型消しゴム";large.shortName="大型";large.price=1250;large.description="大きな下書きに、どんと一面。隣の文字には近づきすぎないこと。減る量も大きめです。";large.role="広い面 / 細部は苦手";large.radius=.50f;large.wearRate=.32f;large.cornerWearRate=.010f;large.crumbAmount=1.3f;large.iconScale=new Vector2(1,1.3f);large.labelColor=new Color(.70f,.36f,.20f);large.contactProfile=game.Catalog.tools[0].contactProfile;large.edgeProfile=Profile("LargeEdge",new Vector2(1,.22f));large.cornerProfile=Profile("LargeCorner",new Vector2(.30f,.30f));EditorUtility.SetDirty(large);}
   var premium=Asset<EraserDefinition>("PremiumEraser",out fresh);
   if(fresh){premium.id="premium";premium.displayName="高級製図消し";premium.shortName="高級製図";premium.price=2600;premium.description="角を長く保ち、紙をいたわる製図用。面は控えめ。消しカス収入と買い替え費用には不向き。";premium.role="長持ちする角 / カス少なめ";premium.radius=.23f;premium.erasePower=1.22f;premium.paperDamageMultiplier=.20f;premium.protectedInkAbrasion=.30f;premium.thinPaperStress=.2f;premium.wearRate=.10f;premium.cornerWearRate=.002f;premium.crumbAmount=.35f;premium.longCrumbPotential=.65f;premium.crumbCohesion=.45f;premium.iconScale=new Vector2(.85f,.58f);premium.bodyColor=new Color(.85f,.89f,.92f);premium.labelColor=new Color(.39f,.29f,.46f);premium.contactProfile=Profile("PremiumFace",new Vector2(.9f,.48f));premium.edgeProfile=Profile("PremiumEdge",new Vector2(.9f,.11f));premium.cornerProfile=Profile("PremiumCorner",new Vector2(.10f,.10f));EditorUtility.SetDirty(premium);}
   var cheap=Asset<EraserDefinition>("BudgetSoftEraser",out fresh);
   if(fresh){cheap.id="budget-soft";cheap.displayName="格安消しゴム片";cheap.shortName="格安消し片";cheap.price=0;cheap.initialRemaining=.35f;cheap.initialSharpness=.30f;cheap.description="使い古しをちぎった小さな消しゴム片。無料でどうぞ。消えにくく、角も丸く、すぐ減ります。何個か受け取って、交換しながら使ってください。";cheap.role="無料の小片 / 消えにくく交換が必要";cheap.erasePower=.40f;cheap.paperDamageMultiplier=.14f;cheap.protectedInkAbrasion=.4f;cheap.radius=.20f;cheap.durability=60;cheap.wearRate=.90f;cheap.cornerWearRate=.065f;cheap.highSpeedRisk=.55f;cheap.thinPaperStress=.15f;cheap.thinPaperPickup=1.3f;cheap.crumbAmount=.65f;cheap.crumbCohesion=.50f;cheap.longCrumbPotential=.60f;cheap.equipment.crumbTolerance=.12f;cheap.reactionMultiplier=.7f;cheap.bodyColor=new Color(.97f,.80f,.74f);cheap.labelColor=new Color(.72f,.48f,.35f);cheap.contactProfile=game.Catalog.tools[0].contactProfile;cheap.edgeProfile=game.Catalog.tools[0].edgeProfile;cheap.cornerProfile=game.Catalog.tools[0].cornerProfile;cheap.iconScale=new Vector2(.8f,.95f);EditorUtility.SetDirty(cheap);}
   // Append missing definitions without deleting a designer's future catalogue entries.
   var list=new System.Collections.Generic.List<EraserDefinition>(game.Catalog.tools);foreach(var d in new[]{thin,large,premium,cheap})if(!list.Contains(d))list.Add(d);game.Catalog.tools=list.ToArray();EditorUtility.SetDirty(game.Catalog);
  }
 }
}
