using System;
using System.IO;
using System.Text;
using UnityEngine;
namespace Keshiya.Editor {
 public static class ShopChecks {
  static int count;static StringBuilder log;
  static void Check(bool ok,string name){count++;log.AppendLine((ok?"PASS: ":"FAIL: ")+name);if(!ok)throw new Exception("SHOP FAIL: "+name);}
  public static void Run(){count=0;log=new StringBuilder();var catalog=Resources.Load<ToolCatalog>("ToolCatalog");var t=System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Take(catalog.tools,7));var m=new PerformanceModifiers();var inventory=new ToolInventory();var wallet=new Wallet();inventory.Initialize(catalog);
   Check(t.Length>=7,"Seven data-driven products");Check(inventory.items.Count==3,"Initial three owned tools");var ids=new System.Collections.Generic.HashSet<string>();
   foreach(var d in t){Check(!string.IsNullOrEmpty(d.id)&&ids.Add(d.id)&&d.price>0&&!string.IsNullOrEmpty(d.description),"Unique purchasable product: "+d.id);Check(d.contactProfile!=null&&d.edgeProfile!=null&&d.cornerProfile!=null,"Three contact profiles: "+d.id);Check(d.durability>0&&d.wearRate>0&&d.cornerWearRate>0&&d.longCrumbPotential>0,"Wear and crumb data: "+d.id);}
   Check(!inventory.Purchase(t[3],wallet,out _)&&inventory.items.Count==3&&wallet.Balance==0,"Insufficient money cannot add inventory");wallet.DebugCredit(10000);long before=wallet.Balance;
   Check(inventory.Purchase(t[3],wallet,out var first)&&wallet.Balance==before-t[3].price,"Purchase debits exact price");Check(inventory.Purchase(t[3],wallet,out var second)&&first.instanceId!=second.instanceId,"Duplicate type has separate identity");first.state.Use(20,ContactMode.Corner,t[3],m);
   Check(first.state.Remaining(t[3],m)<1&&second.state.Remaining(t[3],m)==1,"Individual remaining state");Check(first.state.CornerSharpness<second.state.CornerSharpness,"Individual corner state");Check(first.Condition!="新品"&&second.Condition=="新品","Used and new condition");Check(inventory.Select(second.instanceId)&&inventory.Selected==second,"Select an owned individual");Check(!inventory.Select("missing"),"Cannot select unowned ID");
   second.state.Use(100000,ContactMode.Face,t[3],m);Check(second.state.Exhausted&&second.state.Remaining(t[3],m)==0&&!inventory.Select(second.instanceId),"Exhausted copy is unusable");Check(inventory.OfType(t[3].id)==first,"Type shortcut finds another usable copy");
   Check(inventory.purchases.Count==2&&inventory.Record(t[3].id).purchased,"Purchase history and collection");Check(wallet.JobIncome==0&&wallet.CrumbIncome==0&&wallet.ShopSpent==t[3].price*2,"Shopping and debug funds do not masquerade as job income");
   Check(inventory.Rescue(t[0])==null,"No free replacement while another tool works");foreach(var item in inventory.items)item.state.Use(100000,ContactMode.Face,catalog.Find(item.definitionId),m);var rescue=inventory.Rescue(t[0]);Check(rescue!=null&&rescue.loan&&rescue.state.Remaining(t[0],m)==1,"All-empty rescue provides usable loan");Check(inventory.Rescue(t[0])==null,"Rescue cannot repeatedly create free stock");
   var round=JsonUtility.FromJson<ToolInventory>(JsonUtility.ToJson(inventory));Check(round.items.Count==inventory.items.Count&&round.items[0].state.Exhausted&&round.items[0].instanceId==inventory.items[0].instanceId,"Inventory IDs and exhausted state serialize");Check(round.items[3].state.CornerSharpness==first.state.CornerSharpness&&round.purchases.Count==2,"Corner state and history serialize");
   Check(t[0].erasePower==1.15f&&t[0].paperDamageMultiplier==1&&t[0].radius==.27f,"Ordinary core unchanged");Check(t[2].erasePower==3.6f&&t[2].paperDamageMultiplier==5,"Sand power and danger unchanged");Check(t[1].paperDamageMultiplier<t[0].paperDamageMultiplier&&t[1].longCrumbPotential>t[0].longCrumbPotential,"Soft specialty retained");
   var skills=Resources.Load<SkillCatalog>("SkillCatalog");var config=Resources.Load<ProgressionConfig>("ProgressionConfig");
   foreach(int level in new[]{0,5,10}){var progress=new PlayerProgress(skills,config);progress.DebugPreset(level);var modifiers=new PerformanceModifiers();progress.Apply(modifiers);
    foreach(var d in t){Check(Mathf.Approximately(d.Power(modifiers),d.erasePower*d.equipment.erasePower*modifiers.erasePower)&&Mathf.Approximately(d.DamageMultiplier(modifiers),d.paperDamageMultiplier*d.equipment.paperDamage*d.PaperCare(modifiers.paperDamage)),"Skill power/safety composition Lv"+level+" "+d.id);}
    var fresh=new EraserState();var large=t[4].Contact(modifiers);var narrow=t[3].Contact(modifiers);Check(large.HalfSize.x*large.HalfSize.y>narrow.HalfSize.x*narrow.HalfSize.y*8,"Large face remains broad Lv"+level);Check(t[4].Contact(modifiers,ContactMode.Corner,fresh,0).HalfSize.x>t[3].Contact(modifiers,ContactMode.Corner,fresh,0).HalfSize.x*4,"Large never becomes drafting precision Lv"+level);
    Check(t[6].longCrumbPotential>t[2].longCrumbPotential*modifiers.longGrowth,"Budget soft retains long-crumb advantage over skilled sand Lv"+level);
   }
   Check(t[5].price>t[0].price&&t[5].crumbAmount<t[0].crumbAmount&&t[5].Contact(m).HalfSize.y<t[0].Contact(m).HalfSize.y,"Premium trades money, material and face area for precision");Check(t[6].price<t[0].price&&t[6].erasePower<t[0].erasePower&&t[6].wearRate>t[0].wearRate,"Budget soft is cheap, weak and wears quickly");
   var ec=Resources.Load<CrumbEconomyConfig>("CrumbEconomyConfig");var cheap=new CrumbEconomy(ec);var sand=new CrumbEconomy(ec);ZigzagTestPath.Trace(cheap,t[6]);ZigzagTestPath.Trace(sand,t[2]);Check(cheap.BestLength>sand.BestLength*2,"Actual cheap soft zigzag beats sand for long material");
   var paperConfig=Resources.Load<PrototypeConfig>("PrototypeConfig");var letter=Resources.Load<JobDefinition>("PrecisionJob");
   foreach(int index in new[]{3,5})using(var paper=new Paper(paperConfig,.1f,letter)){var state=new EraserState();for(int pass=0;pass<65&&paper.Drawing.Erased<.95f;pass++)foreach(var path in LetterLayout.Target)for(int k=1;k<path.Length;k++){paper.Stroke(path[k-1],path[k],3,pass,t[index],m,t[index].Contact(m,ContactMode.Corner,state,0));state.Use(Vector2.Distance(path[k-1],path[k]),ContactMode.Corner,t[index],m);}Check(paper.Drawing.Erased>=.95f&&paper.Protection.Loss==0,"New precision tool actually clears letter safely: "+t[index].id);}
   using(var a=new Paper(paperConfig))using(var b=new Paper(paperConfig)){var from=new Vector2(-2,0);var to=new Vector2(2,0);a.Stroke(from,to,4,0,t[4],m,t[4].Contact(m));b.Stroke(from,to,4,0,t[3],m,t[3].Contact(m));Check(a.Drawing.Erased>b.Drawing.Erased,"Large face removes more graphite than narrow tool in equal stroke");}
   foreach(var tool in t){var p0=new PlayerProgress(skills,config);var p10=new PlayerProgress(skills,config);p10.DebugPreset(10);var mm=new PerformanceModifiers();p10.Apply(mm);var raw=new EraserState{allowExhaustion=true};var trained=new EraserState{allowExhaustion=true};raw.Use(10,ContactMode.Corner,tool,m);trained.Use(10,ContactMode.Corner,tool,mm);Check(trained.UsedUnits<raw.UsedUnits&&trained.CornerSharpness>raw.CornerSharpness,"Wear and corner skills apply to "+tool.id);Check(tool.Crumbs(mm)>tool.Crumbs(m)&&tool.Contact(mm).HalfSize.x>tool.Contact(m).HalfSize.x,"Amount and range skills apply to "+tool.id);}
   inventory.DebugFresh();inventory.RecordUse(first,500,12);inventory.RecordUse(first,500,14);inventory.Complete(500,"A");Check(first.jobsUsed==1&&inventory.Record(first.definitionId).uses==1&&inventory.Record(first.definitionId).longestCm==14&&inventory.Record(first.definitionId).bestGrade=="A","Per-tool statistics deduplicate strokes within a job");
   var recording=new PlayerProgress(skills,config);recording.tools.Initialize(catalog);var stream=new CrumbEconomy(ec){Progress=recording};recording.tools.Select(recording.tools.items[1].instanceId);ZigzagTestPath.Trace(stream,t[1]);float length=stream.Growing.LengthCm;recording.tools.Select(recording.tools.items[0].instanceId);stream.EndStroke();Check(recording.tools.items[1].longestCm==length&&recording.tools.items[0].longestCm==0,"Final strand record belongs to original individual after switching");
   Directory.CreateDirectory("TestResults");File.WriteAllText("TestResults/shop-checks.txt",$"PASS {count} shop checks\n"+log);Debug.Log($"KESHIYA_SHOP_CHECKS_OK {count}");
  }
 }
}
