using System;
using System.IO;
using System.Text;
using UnityEngine;
namespace Keshiya.Editor {
 public static class SkillChecks {
  static int count;static StringBuilder log;static SkillCatalog catalog;static ProgressionConfig tuning;
  static void Check(bool ok,string name){if(!ok)throw new Exception("SKILL FAIL: "+name);count++;log.AppendLine("PASS: "+name);}
  static PlayerProgress New()=>new PlayerProgress(catalog,tuning);
  static PerformanceModifiers Mod(int level){var p=New();p.DebugPreset(level);var m=new PerformanceModifiers();p.Apply(m);return m;}
  public static void Run(){count=0;log=new StringBuilder();catalog=Resources.Load<SkillCatalog>("SkillCatalog");tuning=Resources.Load<ProgressionConfig>("ProgressionConfig");var c=Resources.Load<PrototypeConfig>("PrototypeConfig");var ec=Resources.Load<CrumbEconomyConfig>("CrumbEconomyConfig");var tools=Resources.Load<ToolCatalog>("ToolCatalog").tools;var letter=Resources.Load<JobDefinition>("PrecisionJob");
   Check(catalog.skills.Length==11,"Eleven data-driven skills");var seen=new System.Collections.Generic.HashSet<SkillKind>();foreach(var skill in catalog.skills){Check(seen.Add(skill.kind)&&skill.maxLevel==10&&skill.effects.Length==11&&skill.cost==1,"Unique Lv0-10 data: "+skill.title);var p=New();Check(!p.Buy(skill.kind)&&p.Level(skill.kind)==0,"Insufficient branch SP rejected: "+skill.title);p.DebugAddSP(10);int before=p.banks[(int)skill.branch].availableSP;Check(p.Buy(skill.kind)&&p.banks[(int)skill.branch].availableSP==before-1,"Purchase consumes matching branch SP: "+skill.title);for(int i=1;i<10;i++)p.Buy(skill.kind);Check(p.Level(skill.kind)==10&&!p.Buy(skill.kind),"Level cap enforced: "+skill.title);p.ResetSkills();Check(p.Level(skill.kind)==0&&p.banks[(int)skill.branch].availableSP==before,"Reset refunds spent SP: "+skill.title);p.ResetSkills();Check(p.banks[(int)skill.branch].availableSP==before,"Repeated reset cannot duplicate SP: "+skill.title);}
   foreach(CraftBranch branch in Enum.GetValues(typeof(CraftBranch))){var b=New();b.Gain(branch,80,"branch test");Check(b.banks[(int)branch].availableSP==1&&b.banks[((int)branch+1)%3].availableSP==0,"Independent EXP to SP conversion: "+branch);}
   var bank=New();bank.Gain(CraftBranch.Erasing,80,"test");Check(bank.banks[0].earnedSP==1&&bank.banks[0].remainder==0&&bank.banks[1].availableSP==0,"80 EXP grants one SP in only its branch");bank.Gain(CraftBranch.Erasing,95,"test");Check(bank.banks[0].earnedSP==2&&bank.Next(CraftBranch.Erasing)==110,"SP thresholds grow without losing remainder");bank.BeginJob();Check(bank.banks[0].total==175&&bank.jobExp[0]==0,"New job preserves lifetime progress but resets breakdown");
   var p0=New();using(var paper=new Paper(c,.1f,letter)){var m=new PerformanceModifiers();var state=new EraserState();var f=tools[1].Contact(m,ContactMode.Corner,state,0);var result=paper.Stroke(LetterLayout.Target[0][0],LetterLayout.Target[0][1],3,1,tools[1],m,f);Check(result.graphiteArea>0&&result.preciseArea>0&&result.protectedLoss==0,"Actual nearby target removal reports precise graphite");p0.Stroke(result,ContactMode.Corner,true,.76f);Check(p0.banks[0].total>0&&p0.banks[1].total>0,"Real removal earns erasing and precision EXP");float erase=p0.banks[0].total,precision=p0.banks[1].total;for(int i=0;i<1000;i++)p0.Stroke(default,(ContactMode)(i%3),true,1);Check(p0.banks[0].total==erase&&p0.banks[1].total==precision,"Blank rubbing and mode toggling cannot grant EXP");var bad=result;bad.protectedLoss=.01f;p0.Stroke(bad,ContactMode.Edge,true,1);Check(p0.banks[1].total==precision,"Damaging protected ink in the stroke suppresses precision award");}
   var safe=New();var damaged=New();safe.Complete(1,new RewardResult{erased=1},true);damaged.Complete(1,new RewardResult{erased=1,peak=.2f,protectedDamage=.03f},true);Check(safe.banks[1].total>damaged.banks[1].total&&safe.statistics.precisionSuccesses==1,"Safe precision completion grants dedicated bonus");float total=safe.banks[1].total;safe.Complete(1,new RewardResult{erased=1},true);Check(safe.banks[1].total==total,"Completion EXP cannot be claimed twice");
   var shortP=New();var longP=New();shortP.StrandFormed(1,10);longP.StrandFormed(1,30);Check(longP.banks[2].total>shortP.banks[2].total,"Longer strands earn more experience");float earned=longP.banks[2].total;longP.StrandFormed(1,30);Check(longP.banks[2].total==earned,"Repeated detached-piece notification cannot farm EXP");longP.Collected(1,30);float collected=longP.banks[2].total;longP.Collected(1,30);Check(longP.banks[2].total==collected&&collected>earned,"Long collection is rewarded exactly once");longP.Rolled(100);float rolled=longP.banks[2].total;for(int i=0;i<100;i++)longP.Rolled(1);Check(longP.banks[2].total==rolled,"Fine-crumb ball EXP has a job cap");longP.Sold(10000);float sold=longP.banks[2].total;longP.Sold(10000);Check(longP.banks[2].total==sold,"Sales EXP has a job cap");Check(longP.statistics.longestCm==30&&longP.statistics.longCollections==1,"Central statistics record length and collection");
   var zero=Mod(0);var five=Mod(5);var ten=Mod(10);Check(zero.erasePower==.9f&&zero.radius==1&&zero.paperDamage==1&&zero.crumbAmount==1&&zero.wear==1,"Lv0 uses mild efficiency cost and unchanged other baseline multipliers");
   float[] removal=new float[3],damage=new float[3];var mods=new[]{zero,five,ten};for(int k=0;k<3;k++){using(var paper=new Paper(c,.1f,letter)){paper.Stroke(new Vector2(.14f,-.38f),new Vector2(.14f,.38f),3,1,tools[0],mods[k]);removal[k]=paper.Drawing.Erased;}using(var paper=new Paper(c)){paper.Stroke(new Vector2(-.3f,0),new Vector2(.3f,0),30,1,tools[0],mods[k]);damage[k]=paper.AverageDamage;}}
   Check(removal[0]<removal[1]&&removal[1]<removal[2],"Lv0 Lv5 Lv10 erase progressively more with identical input");Check(damage[0]>damage[1]&&damage[1]>damage[2]&&damage[2]>0,"Paper care reduces but does not remove damage");Check(tools[0].Power(ten)<tools[2].Power(zero),"Ordinary max efficiency remains below baseline sand power");
   using(var sand=new Paper(c)){sand.Stroke(new Vector2(-1,0),new Vector2(1,0),45,1,tools[2],ten);Check(sand.PeakDamage>0,"Rough sand erasing is dangerous even at Lv10");}
   var state0=new EraserState();var state10=new EraserState();state0.Use(10,ContactMode.Corner,tools[0],zero);state10.Use(10,ContactMode.Corner,tools[0],ten);Check(state10.UsedUnits>0&&state10.UsedUnits<state0.UsedUnits,"Wear reduction preserves finite consumption");Check(state10.CornerSharpness>state0.CornerSharpness&&state10.CornerSharpness<1,"Corner durability slows rather than removes rounding");
   float regularLoss,careLoss;using(var paper=new Paper(c,.1f,letter)){paper.Stroke(new Vector2(.2f,-.4f),new Vector2(.2f,.4f),4,1,tools[0],zero);regularLoss=paper.Protection.Loss;}var onlyInk=new PerformanceModifiers{protectedGlance=.5f};using(var paper=new Paper(c,.1f,letter)){paper.Stroke(new Vector2(.2f,-.4f),new Vector2(.2f,.4f),4,1,tools[0],onlyInk);careLoss=paper.Protection.Loss;}Check(careLoss>0&&careLoss<regularLoss,"Glancing protected damage is reduced without immunity");
   var face=tools[0].Contact(ten,ContactMode.Face,new EraserState(),0);var edge=tools[0].Contact(ten,ContactMode.Edge,new EraserState(),0);var corner=tools[0].Contact(ten,ContactMode.Corner,new EraserState(),0);Check(face.HalfSize.x*face.HalfSize.y>edge.HalfSize.x*edge.HalfSize.y&&edge.HalfSize.x*edge.HalfSize.y>corner.HalfSize.x*corner.HalfSize.y,"Range skill preserves face edge corner roles");Check(ten.radius==1.15f&&ten.radius<1.2f,"Range growth is modest at maximum level");
   var e0=new CrumbEconomy(ec);var e10=new CrumbEconomy(ec){Skills=ten};ZigzagTestPath.Trace(e0,tools[0]);ZigzagTestPath.Trace(e10,tools[0]);Check(e10.BestLength>e0.BestLength,"Long-growth skill increases actual strand growth");var soft=new CrumbEconomy(ec);ZigzagTestPath.Trace(soft,tools[1]);Check(soft.BestLength>e10.BestLength,"Baseline soft retains advantage over max-skilled ordinary");
   var warning0=new CrumbEconomy(ec);var warning10=new CrumbEconomy(ec){Skills=ten};ZigzagTestPath.Trace(warning0,tools[0],width:.72f,halfSeconds:.25f);ZigzagTestPath.Trace(warning10,tools[0],width:.72f,halfSeconds:.25f);Check(warning10.Motion.Risk<warning0.Motion.Risk,"Continuity lowers tension on imperfect rubbing");e10.Stroke(new Vector2(4,.18f),new Vector2(7,2),100,tools[0],ContactMode.Face,1,.01f);Check(e10.Growing==null&&e10.BreakCount>0,"Extreme motion still cuts at maximum continuity");
   var amount0=new CrumbEconomy(ec);var amount10=new CrumbEconomy(ec);amount0.Stroke(Vector2.zero,Vector2.right,4,tools[0],ContactMode.Corner,tools[0].Crumbs(zero),.1f);amount10.Stroke(Vector2.zero,Vector2.right,4,tools[0],ContactMode.Corner,tools[0].Crumbs(ten),.1f);Check(Mathf.Abs(amount10.ProducedGrams/amount0.ProducedGrams-1.3f)<.001f,"Crumb quantity increases internal material by 30 percent at Lv10");
   var b0=new CrumbEconomy(ec);var b10=new CrumbEconomy(ec){Skills=ten,Progress=New()};foreach(var e in new[]{b0,b10}){e.Stroke(Vector2.zero,Vector2.right,4,tools[0],ContactMode.Corner,1,.1f);e.Collect();e.Roll();}Check(b10.Ball.Grams>b0.Ball.Grams&&Mathf.Abs(b10.Ball.Grams/b0.Ball.Grams-1.2f)<.001f,"Ball efficiency adds a bounded 20 percent yield");Check(Mathf.Abs(b10.ProducedGrams-b10.AccountedMass)<.001f&&b10.ConversionBonusGrams>0,"Ball yield bonus is explicitly accounted as converted material");float ball=b10.Ball.Grams,xp=b10.Progress.banks[2].total;Check(!b10.Roll()&&b10.Ball.Grams==ball&&b10.Progress.banks[2].total==xp,"Empty repeat rolling cannot create weight or EXP");
   var white=new CrumbEconomy(ec){Skills=ten,Progress=New()};ZigzagTestPath.Trace(white,tools[1],graphitePerUnit:0);white.Collect();white.Roll();Check(white.ProducedGrams==0&&white.Progress.banks[2].total==0,"All crumb skills still require erased graphite");
   using(var paper=new Paper(c,.1f,letter)){float erased=paper.Drawing.Erased,loss=paper.Protection.Loss;var before=paper.Texture.GetPixels32();paper.Reveal(.4f);var after=paper.Texture.GetPixels32();int changed=0;for(int i=0;i<before.Length;i++)if(!before[i].Equals(after[i]))changed++;Check(changed>0&&paper.Drawing.Erased==erased&&paper.Protection.Loss==loss,"Sensing changes only visualization, not target or protection state");paper.Reveal(0);var restored=paper.Texture.GetPixels32();bool same=true;for(int i=0;i<before.Length;i++)if(!before[i].Equals(restored[i])){same=false;break;}Check(same,"Sensing display restores original paper colors");}
   Check(catalog.Find(SkillKind.Sense).Effect(1)==.9f&&Mathf.Abs(catalog.Find(SkillKind.Sense).Effect(10)-.6f)<.0001f,"Sensing unlocks earlier in cleanup at high levels");
   Directory.CreateDirectory("TestResults");File.WriteAllText("TestResults/skill-checks.txt",$"PASS {count} skill checks\n"+log);Debug.Log($"SKILL_CHECKS_OK {count}");
  }
 }
}
