using System;
using System.IO;
using System.Text;
using System.Linq;
using UnityEngine;
namespace Keshiya.Editor {
 public static class SpecialistChecks {
  static int count;static StringBuilder log,metrics;static PrototypeConfig config;static EraserDefinition[] tools;static PerformanceModifiers zero;
  static void Check(bool ok,string text){count++;log.AppendLine((ok?"PASS: ":"FAIL: ")+text);File.WriteAllText("TestResults/specialist-checks.txt",$"Checks={count}\n"+log);if(!ok)throw new Exception("SPECIALIST FAIL: "+text);}
  static JobDefinition J(string id)=>Resources.Load<JobDefinition>("Specialist-"+id);
  static PaperDefinition P(string id)=>Resources.Load<PaperDefinition>("Paper-"+id);
  static WritingInstrumentDefinition W(string id)=>Resources.Load<WritingInstrumentDefinition>("Writing-"+id);
  static JobDefinition Sample(string paper,string writing){var j=ScriptableObject.CreateInstance<JobDefinition>();j.paper=P(paper);j.writing=W(writing);j.customDrawing=true;j.targetPaths=new[]{new JobPath(new[]{new Vector2(-.8f,0),new Vector2(.8f,0)})};return j;}
  static PlayerProgress Progress()=>new PlayerProgress(Resources.Load<SkillCatalog>("SkillCatalog"),Resources.Load<ProgressionConfig>("ProgressionConfig"));
  static float Damage(JobDefinition job,int tool){using(var p=new Paper(config,0,job)){for(int i=0;i<7;i++)p.Stroke(new Vector2(-.25f,0),new Vector2(.25f,0),18,i*.05f,tools[tool],zero);return p.AverageDamage;}}
  static float Sweep(JobDefinition job,int tool){using(var p=new Paper(config,0,job)){for(float y=-1.9f;y<2;y+=.32f)p.Stroke(new Vector2(-2.85f,y),new Vector2(2.85f,y),4,1,tools[tool],zero);return p.Drawing.Erased;}}
  static void Complete(JobDefinition job,int tool,ContactMode mode,float yaw=0,bool worn=false){
   using(var p=new Paper(config,.1f,job)){var state=new EraserState();if(worn)state.DebugSharpness(.1f);var progress=Progress();int pass=0;for(;pass<180&&p.Drawing.Erased<.985f;pass++){
    if(job.precision){foreach(var path in job.targetPaths)for(int n=1;n<path.points.Length;n++){var a=path.points[n-1];var b=path.points[n];if(pass%2==1){var tmp=a;a=b;b=tmp;}var stroke=p.Stroke(a,b,3,pass,tools[tool],zero,tools[tool].Contact(zero,mode,state,yaw));progress.Stroke(stroke,mode,true,Vector2.Distance(a,b));state.Use(Vector2.Distance(a,b),mode,tools[tool],zero);}}
    else {for(float y=-2;y<=2;y+=.2f){var a=new Vector2(-2.9f,y);var b=new Vector2(2.9f,y);p.Stroke(a,b,4,pass,tools[tool],zero);state.Use(5.8f,mode,tools[tool],zero);}}
   }
   if(job.id=="close-letter"&&tool==3)Check(state.CornerSharpness>.1f,"One small letter does not exhaust the drafting corner");
   metrics.AppendLine($"{job.id} {tools[tool].id} {mode} worn={worn}: passes={pass} erased={p.Drawing.Erased:P3} protected={p.Protection?.Loss??0:P3} sharpness={state.CornerSharpness:F3} remaining={state.Remaining(tools[tool],zero):F3}");File.WriteAllText("TestResults/specialist-measurements.txt",metrics.ToString());
   var work=new Job(config,job);work.StartWork();work.Tick(100000);Check(work.Complete(p)&&p.Drawing.Erased>=.95f,"Real strokes complete "+job.id+" / "+tools[tool].id+(worn?" worn":""));Check((p.Protection?.Loss??0)<=.005f&&p.PeakDamage==0,"Protected artwork and paper survive "+job.id+" / "+tools[tool].id);
   Check(work.Result.basic==job.baseReward&&work.Result.speed==0&&WorkSession.Grade(work.Result)=="S","Skilled slow work can earn S and full base / "+job.id);
   if(job.precision){Check(progress.jobExp[1]>0,"Localized precision work earns EXP / "+job.id);Check(state.CornerSharpness<1,"Specialist work consumes corner / "+job.id);}
  }}
  static void MixedManga(){var job=J("manga");using(var p=new Paper(config,.1f,job)){var state=new EraserState();bool[] done=new bool[job.targetPaths.Length];float travel=0;int pass=0;
    for(;pass<100&&p.Drawing.Erased<.98f;pass++)for(int k=0;k<job.targetPaths.Length;k++){if(done[k])continue;var path=job.targetPaths[k].points;int part=k%10;var a=path[0];var b=path[1];float removed=0;
     if(part==2||part==3){var cut=Vector2.Lerp(a,b,part==2?.6f:.4f);var first=part==2?ContactMode.Edge:ContactMode.Corner;var second=part==2?ContactMode.Corner:ContactMode.Edge;float angle=part==2?45:-45;removed+=Rub(p,a,cut,first,angle,state,pass);removed+=Rub(p,cut,b,second,angle,state,pass);}
     else removed=Rub(p,a,b,part<2?ContactMode.Edge:ContactMode.Face,part==1?90:0,state,pass);
     travel+=Vector2.Distance(a,b);if(removed<.000001f)done[k]=true;
    }
    metrics.AppendLine($"Manga mixed tools: erased={p.Drawing.Erased:P3} protected={p.Protection.Loss:P3} travel={travel:F3} sharpness={state.CornerSharpness:F3}");
    Check(p.Drawing.Erased>=.95f&&p.Protection.Loss<.005f,"Manga completes with face in open space, aligned edge near lines, corner near intersections");Check(state.CornerSharpness>.15f,"Using mixed contact modes conserves the ordinary corner on manga");
   }}
  static float Rub(Paper p,Vector2 a,Vector2 b,ContactMode mode,float yaw,EraserState state,int time){var r=p.Stroke(a,b,3,time,tools[0],zero,tools[0].Contact(zero,mode,state,yaw));state.Use(Vector2.Distance(a,b),mode,tools[0],zero);return r.erasedFraction;}
  public static void Run(){Directory.CreateDirectory("TestResults");count=0;log=new StringBuilder();metrics=new StringBuilder();config=Resources.Load<PrototypeConfig>("PrototypeConfig");tools=Resources.Load<ToolCatalog>("ToolCatalog").tools;zero=new PerformanceModifiers();Progress().Apply(zero);
   Check(Resources.LoadAll<PaperDefinition>("").Length>=5,"At least five paper assets");Check(Resources.LoadAll<WritingInstrumentDefinition>("").Length>=5,"At least five writing assets");
   foreach(var p in Resources.LoadAll<PaperDefinition>(""))Check(p.thickness>0&&p.durability>0&&p.localWearResistance>0&&!string.IsNullOrEmpty(p.description),"Paper data complete / "+p.id);
   foreach(var w in Resources.LoadAll<WritingInstrumentDefinition>(""))Check(w.density>0&&w.erasability>0&&w.crumbModifier>0&&!string.IsNullOrEmpty(w.recommendedTools),"Writing data complete / "+w.id);
   var baseline=Sample("ordinary","hb");Check(P("ordinary").DamageScale==1&&P("ordinary").surfaceDrag==1&&W("hb").Mass(1)==1&&W("hb").Removal(1)==1,"Ordinary x HB is numerically neutral");
   float normal=Damage(baseline,0);var thin=Sample("thin","hb");var drawing=Sample("drawing","hb");var old=Sample("old","hb");Check(Damage(thin,0)>normal,"Thin paper receives more damage");Check(Damage(drawing,0)<normal,"Drawing paper withstands rough broad work");Check(P("old").localWearResistance<P("thin").localWearResistance&&Damage(old,0)>Damage(thin,0),"Old paper is vulnerable to focused rubbing");Check(Damage(old,1)<Damage(old,0)*.3f,"Soft is substantially safer on old paper");Check(Damage(old,5)<Damage(old,0)*.3f,"Premium safety helps delicate work");Check(Damage(baseline,2)>normal*3,"Sand remains risky");
   using(var p=new Paper(config,0,old)){p.Stroke(Vector2.zero,Vector2.right*.5f,3,1,tools[0],zero);Check(p.PeakDamage==0,"Old paper does not break from gentle contact");}
   float hb=0,colored=0;foreach(var id in new[]{"hb","2b","4b","mechanical","colored"}){var j=Sample("ordinary",id);using(var p=new Paper(config,0,j)){float mass=p.Drawing.InitialMass;p.Stroke(new Vector2(-.8f,0),new Vector2(.8f,0),4,1,tools[0],zero);metrics.AppendLine($"{id}: mass={mass:F3}, one stroke erasure={p.Drawing.Erased:P3}");if(id=="hb")hb=p.Drawing.Erased;if(id=="colored")colored=p.Drawing.Erased;Check(p.Drawing.Erased>0&&p.Drawing.Erased<1,"Every writing instrument is erasable / "+id);}UnityEngine.Object.DestroyImmediate(j);}
   Check(colored<hb*.7f,"Colored pencil takes more rubbing than HB");Check(W("4b").density>W("2b").density&&W("2b").density>W("hb").density,"Soft pencils carry more actual removable mass");Check(W("mechanical").lineWidth<1&&W("mechanical").Removal(1.5f)<W("mechanical").Removal(.5f),"Mechanical pencil is fine and strong pressure resists erasure");Check(W("colored").crumbModifier<1&&W("2b").crumbModifier>1,"Material crumb yield distinguishes graphite from colored marks");
   var jobs=Resources.LoadAll<JobDefinition>("");Check(jobs.Length>=12&&jobs.Select(j=>j.id).Distinct().Count()==jobs.Length,"Twelve unique contracts");foreach(var j in jobs){Check(j.paper!=null&&j.writing!=null&&j.requiredErasure==.95f&&j.baseReward>0,"Formal paper and writing references / "+j.id);}
   string[] added={"close-letter","extra-stroke","ruled-margin","manga","large-study","old-letter","color-doodle"};foreach(var id in added)Check(J(id)!=null&&J(id).targetPaths.Length>0,"New specialist content / "+id);
   Complete(J("close-letter"),0,ContactMode.Corner);Complete(J("close-letter"),3,ContactMode.Corner);Complete(J("close-letter"),0,ContactMode.Corner,worn:true);Complete(J("extra-stroke"),3,ContactMode.Corner);Complete(J("extra-stroke"),0,ContactMode.Corner);Complete(J("ruled-margin"),0,ContactMode.Edge,45);Complete(J("manga"),0,ContactMode.Corner);Complete(J("old-letter"),0,ContactMode.Corner);Complete(J("old-letter"),1,ContactMode.Corner);Complete(J("large-study"),0,ContactMode.Face);Complete(J("color-doodle"),0,ContactMode.Face);
   var slipJob=J("extra-stroke");var start=slipJob.targetPaths[0].points[0]-Vector2.right*.025f;var end=start+Vector2.up*.12f;float narrowLoss,ordinaryLoss,wornLoss;
   using(var a=new Paper(config,0,slipJob))using(var b=new Paper(config,0,slipJob))using(var d=new Paper(config,0,slipJob)){var worn=new EraserState();worn.DebugSharpness(.1f);a.Stroke(start,end,3,1,tools[3],zero,tools[3].Contact(zero,ContactMode.Corner,new EraserState(),0));b.Stroke(start,end,3,1,tools[0],zero,tools[0].Contact(zero,ContactMode.Corner,new EraserState(),0));d.Stroke(start,end,3,1,tools[0],zero,tools[0].Contact(zero,ContactMode.Corner,worn,0));narrowLoss=a.Protection.Loss;ordinaryLoss=b.Protection.Loss;wornLoss=d.Protection.Loss;Check(narrowLoss==0&&ordinaryLoss>0,"Narrow drafting corner tolerates a small slip beside F");Check(wornLoss>ordinaryLoss,"Fresh corner gives more margin than rounded corner");}
   MixedManga();
   float alignedLoss,wrongLoss,faceLoss;var ruled=J("ruled-margin");var line=ruled.targetPaths[0].points;using(var a=new Paper(config,0,ruled))using(var b=new Paper(config,0,ruled))using(var c=new Paper(config,0,ruled)){a.Stroke(line[0],line[1],4,1,tools[0],zero,tools[0].Contact(zero,ContactMode.Edge,new EraserState(),45));b.Stroke(line[0],line[1],4,1,tools[0],zero,tools[0].Contact(zero,ContactMode.Edge,new EraserState(),0));c.Stroke(line[0],line[1],4,1,tools[0],zero,tools[0].Contact(zero));alignedLoss=a.Protection.Loss;wrongLoss=b.Protection.Loss;faceLoss=c.Protection.Loss;Check(alignedLoss==0&&wrongLoss>0&&faceLoss>wrongLoss,"Rotated edge follows diagonal while wrong edge and face damage rules");}
   Check(Sweep(J("large-study"),4)>Sweep(J("large-study"),0)*1.3f,"Large face removes more dense sketch in equal travel");Check(Sweep(J("large-study"),0)>Sweep(J("large-study"),5),"Premium remains inefficient on broad dense sketches");
   var plain=Progress();using(var paper=new Paper(config,0,baseline)){for(int i=0;i<50;i++){var r=paper.Stroke(new Vector2(-.8f,0),new Vector2(.8f,0),4,i,tools[0],zero,tools[0].Contact(zero,ContactMode.Corner,new EraserState(),0));plain.Stroke(r,ContactMode.Corner,false,1.6f);}Check(plain.jobExp[0]>0&&plain.jobExp[1]==0,"Corner rubbing in open space cannot farm precision EXP");}
   var max=Progress();max.DebugPreset(10);var modifiers=new PerformanceModifiers();max.Apply(modifiers);var fresh=new EraserState();var skilled=new EraserState();fresh.Use(20,ContactMode.Corner,tools[0],zero);skilled.Use(20,ContactMode.Corner,tools[0],modifiers);Check(skilled.CornerSharpness>fresh.CornerSharpness&&skilled.CornerSharpness<1,"Existing corner durability retains finite advantage");using(var p=new Paper(config,0,Resources.Load<JobDefinition>("PrecisionJob"))){var earned=Progress();float totalFraction=0;for(int pass=0;pass<55;pass++)foreach(var path in LetterLayout.Target)for(int n=1;n<path.Length;n++){var r=p.Stroke(path[n-1],path[n],3,pass,tools[1],zero,tools[1].Contact(zero,ContactMode.Corner,new EraserState(),0));totalFraction+=r.preciseFraction;earned.Stroke(r,ContactMode.Corner,true,Vector2.Distance(path[n-1],path[n]));}earned.Complete(1,new RewardResult{erased=1},true);Check(totalFraction<=1.001f&&totalFraction>.9f,"Precision progress is bounded by original local graphite");Check(earned.banks[1].availableSP>0,"Careful letter work retains the previous first precision SP pace");}
   Check(tools[5].price==7800&&modifiers.erasePower==1.85f&&zero.erasePower==.9f,"Existing prices and skill balance preserved");
   var r0=new RewardResult{erased=1,peak=.008f,qualitySensitivity=1};var r1=r0;r1.qualitySensitivity=2;Check(WorkSession.Grade(r0)=="S"&&WorkSession.Grade(r1)=="A","Fine paper makes visible damage count more in grade");Check(jobs.Where(j=>j.id.Contains("-")).All(j=>j.baseReward+config.finishBonus+config.pristineBonus+config.speedBonus+j.protectionBonus<3900),"New job rewards do not buy premium within two clean jobs");
   foreach(var j in new[]{baseline,thin,drawing,old})UnityEngine.Object.DestroyImmediate(j);
   File.WriteAllText("TestResults/specialist-measurements.txt",metrics.ToString());File.WriteAllText("TestResults/specialist-checks.txt",$"PASS {count} specialist checks\n"+log);Debug.Log($"SPECIALIST_CHECKS_OK {count}");
  }
 }
}
