using System.Collections;
using System.IO;
using System.Text;
using UnityEngine;
namespace Keshiya {
 public sealed class RuntimeSkillChecks:MonoBehaviour {
  public PrototypeGame Game;int count,fail;string directory;readonly StringBuilder report=new StringBuilder();
  void Awake(){Application.runInBackground=true;}
  void Check(bool ok,string name){count++;if(!ok)fail++;report.AppendLine((ok?"PASS: ":"FAIL: ")+name);Debug.Log((ok?"PASS: ":"FAIL: ")+name);}
  IEnumerator Capture(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(directory,name+".png"));yield return new WaitForSecondsRealtime(.25f);}
  IEnumerator Start(){directory=Path.Combine(Application.dataPath,"../TestResults-0.5");Directory.CreateDirectory(directory);Game.Controller.ExternalInput=true;yield return new WaitForSecondsRealtime(.7f);
   Check(Game.BoardEnabled&&Game.Session.Phase==WorkPhase.Board,"New game keeps five-job board");Game.Controller.HandleKeyDown(KeyCode.K);Check(Game.SkillsOpen&&Game.InputBlocked&&!Game.SkillsHUD.DebugVisible,"K opens optional skill screen with debug hidden");yield return Capture("01-new-skills");Check(!Game.BuySkill(SkillKind.Efficiency),"Fresh player cannot buy without SP");Game.Controller.HandleKeyDown(KeyCode.K);Check(!Game.SkillsOpen&&Game.InputBlocked,"Closing skills returns to blocked board");
   Game.ChooseJob(1);Game.BeginWork();Game.SelectTool(1);Game.SelectMode(ContactMode.Corner);for(int pass=0;pass<45&&!Game.CurrentJob.CanComplete(Game.Paper);pass++){foreach(var path in LetterLayout.Target)for(int k=1;k<path.Length;k++)Game.Rub(path[k-1],path[k],3);yield return null;}
   Check(Game.Progress.jobExp[0]>0&&Game.Progress.jobExp[1]>0,"Actual letter work grants erasing and precision EXP");Check(Game.Paper.Protection.Loss==0&&Game.CurrentJob.CanComplete(Game.Paper),"Lv0 letter still safely completes");Game.CurrentJob.Tick(10000);long money=Game.Economy.Wallet.Balance;Game.Finish();Check(Game.Progress.statistics.precisionSuccesses==1&&Game.Progress.statistics.pristineJobs==1,"Safe completion updates central statistics");Check(Game.Economy.Wallet.Balance==money+Game.CurrentJob.Result.Total&&Game.CurrentJob.Result.speed==0,"Growth does not change slow-job reward rules");float exp=Game.Progress.banks[1].total;Game.Finish();Check(Game.Progress.banks[1].total==exp,"Repeated completion does not duplicate experience");yield return Capture("02-earned-result");
   Game.OpenSkills();Check(Game.Progress.banks[1].availableSP>0,"A precision job naturally earns precision SP");int sp=Game.Progress.banks[1].availableSP;money=Game.Economy.Wallet.Balance;Check(Game.BuySkill(SkillKind.Sense)&&Game.Progress.banks[1].availableSP==sp-1&&Game.Economy.Wallet.Balance==money,"Acquisition spends branch SP and never money");Game.SkillsHUD.SelectBranch(CraftBranch.Precision);Check(Game.SkillsHUD.SelectedBranch==CraftBranch.Precision,"Precision tab selected with earned skill");yield return Capture("03-earned-skills");Game.ResetSkills();Check(Game.Progress.Level(SkillKind.Sense)==0&&Game.Progress.banks[1].availableSP==sp&&Game.Progress.banks[1].total==exp,"Prototype respec returns SP and preserves earned EXP");Game.CloseSkills();
   float[] removed=new float[3];int[] levels={0,5,10};for(int i=0;i<3;i++){Game.Progress.DebugPreset(levels[i]);Game.RefreshSkills();Game.ChooseJob(1);Game.BeginWork();Game.SelectTool(0);Game.SelectMode(ContactMode.Face);Game.Rub(new Vector2(.14f,-.38f),new Vector2(.14f,.38f),3);removed[i]=Game.Paper.Drawing.Erased;Check(Game.Presentation.Footprint.HalfSize==Game.Contact.HalfSize,"Visible sole follows range skill Lv"+levels[i]);yield return Capture("04-level-"+levels[i]);}
   Check(removed[0]<removed[1]&&removed[1]<removed[2],"Identical rubbing removes more at Lv0 Lv5 Lv10");Game.OpenSkills();float erased=Game.Paper.Drawing.Erased;Game.Rub(Vector2.zero,Vector2.one,4);Check(Game.Paper.Drawing.Erased==erased,"Skill overlay prevents accidental work");Game.SkillsHUD.SelectBranch(CraftBranch.Erasing);yield return Capture("05-max-skills");Game.SkillsHUD.SelectBranch(CraftBranch.Precision);yield return Capture("05b-precision-max");Game.SkillsHUD.SelectBranch(CraftBranch.Crumbs);Check(Game.SkillsHUD.SelectedBranch==CraftBranch.Crumbs,"Crumb tab exposes its separate skill branch");yield return Capture("05c-crumb-max");Game.SkillsHUD.ToggleDebug();Check(Game.SkillsHUD.DebugVisible,"Comparison debug can be explicitly enabled");yield return Capture("05d-debug");Game.SkillsHUD.ToggleDebug();Game.CloseSkills();
   Game.ChooseJob(0);Game.BeginWork();Game.SelectTool(0);Game.SelectMode(ContactMode.Face);Check(!Game.Sense(),"Fresh paper does not reveal even with maximum sensing");for(int pass=0;pass<8&&Game.Paper.Drawing.Erased<.80f;pass++){for(float y=-2;y<=2&&Game.Paper.Drawing.Erased<.85f;y+=.15f)Game.Rub(new Vector2(-2.9f,y),new Vector2(2.9f,y),4);yield return null;}
   Game.Controller.HandleKeyDown(KeyCode.F);Check(Game.Paper.RevealStrength>0&&Game.SenseUntil>Time.unscaledTime,"F briefly reveals remaining target at high cleanup");yield return Capture("06-sense");yield return new WaitForSecondsRealtime(Game.SkillDefinitions.Find(SkillKind.Sense).Duration(10)+.3f);Check(Game.Paper.RevealStrength==0,"Sensing naturally expires");
   Game.Progress.DebugPreset(0);Game.RefreshSkills();Game.ChooseJob(4);Game.BeginWork();Game.SelectTool(1);Game.SelectMode(ContactMode.Face);Vector2 a=new Vector2(-2.5f,-1.53f);Game.Controller.ProcessInput(a,true,true,.02f);
   for(int leg=0;leg<40;leg++){Vector2 b=new Vector2(-2.5f+(leg+1)*.12f,-1.35f+(leg%2==0?.18f:-.18f));for(int part=1;part<=6;part++){Game.Controller.ProcessInput(Vector2.Lerp(a,b,part/6f),true,true,.14f/6);yield return null;}a=b;}
   Game.Controller.ProcessInput(a,false,true,.02f);Check(Game.Economy.BestLength>=5&&Game.Progress.banks[2].total>0,"Actual advancing zigzag creates strand EXP");Game.CollectCrumbs();Check(Game.Progress.statistics.longCollections>0,"Actual C-equivalent collection grants length experience");float crumbExp=Game.Progress.banks[2].total;Game.CollectCrumbs();Check(Game.Progress.banks[2].total==crumbExp,"Repeated empty collection cannot farm EXP");Game.RollCrumbs();Game.OpenTrade();Game.Economy.SellLongs();Game.Economy.SellBall();Check(Game.Progress.banks[2].total>crumbExp&&Game.Economy.Wallet.CrumbIncome>0,"Rolling and selling add capped craft experience and separate money");yield return Capture("07-crumb-trade");Game.CloseTrade();Game.OpenSkills();Game.SkillsHUD.SelectBranch(CraftBranch.Crumbs);yield return Capture("08-session-progress");
   File.WriteAllText(Path.Combine(directory,"runtime.txt"),report+$"Checks={count}; Failures={fail}; Erase0={removed[0]}; Erase5={removed[1]}; Erase10={removed[2]}\n");Application.Quit(fail==0?0:1);
  }
 }
}
