using System.Collections;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;
namespace Keshiya {
 public sealed class RuntimeWorldChecks:MonoBehaviour {
  public PrototypeGame Game;int count,fail;string dir;readonly StringBuilder report=new StringBuilder();
  void Awake(){Application.runInBackground=true;}
  void Check(bool ok,string text){count++;if(!ok)fail++;report.AppendLine((ok?"PASS: ":"FAIL: ")+text);Debug.Log((ok?"PASS: ":"FAIL: ")+text);File.WriteAllText(Path.Combine(dir,"runtime.txt"),report+$"Checks={count}; Failures={fail}\n");}
  IEnumerator Capture(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return new WaitForSecondsRealtime(.25f);}
  IEnumerator Start(){dir=Path.Combine(Application.dataPath,"../TestResults-0.8");Directory.CreateDirectory(dir);Game.Controller.ExternalInput=true;yield return new WaitForSecondsRealtime(.7f);
   Check(Game.Jobs.Count(x=>!x.externalTest)==20&&Game.Session.Phase==WorkPhase.Board,"Twenty jobs available at startup");Check(!Game.Tools.loadout.limited&&Game.Tools.loadout.capacity==5,"Default unrestricted carry, optional five-tool capacity");Game.SetCarryLimit(true);Game.WorkHUD.BoardScroll=new Vector2(0,1600);yield return Capture("01-world-board");
   Game.OpenShop();Game.ShopHUD.SetCategory("パン");yield return Capture("02-bread-shop");Game.Economy.Wallet.DebugCredit(50000);for(int i=7;i<16;i++){long before=Game.Economy.Wallet.Balance;Check(Game.PurchaseTool(i)&&Game.Economy.Wallet.Balance==before-Game.Catalog.tools[i].price,"Purchase new tool "+i);}Check(!Game.PurchaseTool(16),"Quest supply cannot be purchased");Check(Game.Tools.CollectedSeries(Game.Catalog,"パンシリーズ")==3,"Bread series complete");Game.ShopHUD.CollectionOpen=true;yield return Capture("03-collection");Game.CloseShop();
   var sixth=Game.Tools.items.Last();Check(Game.Tools.loadout.selected.Count==5&&!Game.ToggleCarry(sixth.instanceId),"Five packed tools reject sixth");Game.ChooseJob(0);Game.BeginWork();Check(!Game.SelectOwned(sixth.instanceId),"Unpacked tool cannot be selected at work");Check(!Game.ToggleCarry(sixth.instanceId),"Packing locked during work");Game.SetCarryLimit(false);Check(Game.Tools.loadout.limited,"Limit cannot change during work");Game.ShowBoard();Game.SetCarryLimit(false);Game.ChooseJob(0);Game.BeginWork();Check(Game.SelectOwned(sixth.instanceId),"Unlimited mode permits later items");Game.ShowBoard();Game.SetCarryLimit(true);
   foreach(var item in Game.Tools.items.Where(x=>Game.Tools.loadout.Contains(x.instanceId)))item.state.DebugRemaining(0,Game.Catalog.Find(item.definitionId),Game.Modifiers);
   Game.ChooseJob(0);Game.BeginWork();Check(Game.HasUsableTool&&Game.ActiveTool.loan&&Game.Tools.loadout.selected.Count<=5,"Exhausted packed tools receive rescue without softlock");Game.ShowBoard();Game.Tools.DebugFresh();Game.SetCarryLimit(false);
   for(int index=12;index<20;index++){Game.ChooseJob(index);yield return Capture("04-detail-"+index);Game.SelectTool(0);Game.BeginWork();Game.SelectMode(ContactMode.Corner);Check(Game.JobIndex==index&&!Game.InputBlocked,"New job starts "+index);yield return Capture("05-work-"+index);
    string suppliedId=null;int stock=Game.Tools.items.Count;if(index==12){suppliedId=Game.ActiveTool.instanceId;Check(Game.Supplied!=null&&!Game.Tools.items.Contains(Game.Supplied),"Supply separate from personal stock");Check(!Game.SelectOwned(Game.Tools.items[0].instanceId),"Named task uses supplied tool");float left=Game.ActiveState.Remaining(Game.Eraser,Game.Modifiers);Game.Rub(new Vector2(-2.8f,1.95f),new Vector2(-2.5f,1.95f),3);Check(Game.CurrentJob.SupplyProgress==0&&Mathf.Approximately(left,Game.ActiveState.Remaining(Game.Eraser,Game.Modifiers)),"White paper cannot consume supplied objective");}
    for(int pass=0;pass<180&&!Game.CurrentJob.CanComplete(Game.Paper);pass++){if(!Game.HasUsableTool&&Game.Supplied==null){Game.NextTool();Game.BorrowTool();}foreach(var path in Game.Definition.targetPaths)for(int n=1;n<path.points.Length;n++)Game.Rub(pass%2==0?path.points[n-1]:path.points[n],pass%2==0?path.points[n]:path.points[n-1],3);yield return null;}
    Check(Game.CurrentJob.CanComplete(Game.Paper),"Real strokes complete new job "+index+$" erased={Game.Paper.Drawing.Erased:F6} supply={Game.CurrentJob.SupplyProgress:F6} remaining={Game.ActiveState.Remaining(Game.Eraser,Game.Modifiers):F4}");Check(Game.Paper.PeakDamage<.1f&&(Game.Paper.Protection?.Loss??0)<.05f,"Careful work preserves paper and protected content "+index);
    if(index==12)Check(Game.CurrentJob.SupplyProgress==1&&Game.ActiveState.Exhausted,"Named remainder genuinely finishes at objective");
    long cash=Game.Economy.Wallet.Balance;Game.CurrentJob.Tick(100000);Game.Finish();Check(Game.Session.Phase==WorkPhase.Result&&Game.CurrentJob.Result.basic==Game.Definition.baseReward&&Game.CurrentJob.Result.speed==0&&Game.Economy.Wallet.Balance==cash+Game.CurrentJob.Result.Total,"Slow completion earns base and result "+index);
    var record=Game.Session.Record(Game.Definition.id);Check(record!=null&&record.lastUsage.Count>0&&record.lastUsage.Sum(x=>x.graphiteArea)>0&&record.lastUsage.Sum(x=>x.contactSeconds)>0,"Result records tool usage "+index);
    if(index==12){Check(Game.Supplied==null&&Game.Tools.items.Count==stock&&record.lastUsage[0].instanceId==suppliedId&&record.lastUsage[0].supplied,"Supply returned; historical identity retained");yield return Capture("06-named-result");}
    Game.ShowBoard();Game.Tools.DebugFresh();
   }
   Game.ChooseJob(12);Game.BeginWork();string aborted=Game.Supplied.instanceId;Game.ShowBoard();Check(Game.Supplied==null,"Abort removes temporary supply");Game.ChooseJob(12);Game.BeginWork();Check(Game.Supplied.instanceId!=aborted&&Game.CurrentJob.SupplyProgress==0,"Retry supplies independent fresh remainder");Game.ShowBoard();
   foreach(int tool in new[]{14,15}){Game.ChooseJob(18);Game.SelectTool(tool);Game.BeginWork();Game.SelectMode(ContactMode.Face);float mass=Game.Economy.ProducedGrams;var original=Game.ActiveState.special.Color(Game.Eraser);for(int p=0;p<4;p++){foreach(var path in Game.Definition.targetPaths)for(int k=1;k<path.points.Length;k++)Game.Rub(path.points[k-1],path.points[k],3);yield return null;}Check(Game.Paper.Drawing.Erased>0,"Special tool erases graphite "+tool);Check(Game.ActiveState.special.Color(Game.Eraser)!=original,"Use visibly changes state color "+tool);if(tool==14){Check(Game.ActiveState.special.graphiteLoad>0&&Game.ActiveState.special.toastLevel==0,"Kneaded absorbs graphite");Check(Game.Economy.ProducedGrams==mass,"Kneaded does not produce ordinary tradable crumbs");}else Check(Game.ActiveState.special.toastLevel>0&&Game.ActiveState.special.graphiteLoad==0,"Bread hardens independently");yield return Capture("07-special-"+tool);Game.ShowBoard();}
   Game.PurchaseTool(4);float ordinary=0;foreach(int tool in new[]{0,4}){Game.ChooseJob(18);Game.SelectTool(tool);Game.BeginWork();Game.SelectMode(ContactMode.Face);for(float y=-1.8f;y<2;y+=.5f)Game.Rub(new Vector2(-2.8f,y),new Vector2(2.8f,y),4);if(tool==0)ordinary=Game.Paper.Drawing.Erased;else Check(Game.Paper.Drawing.Erased>ordinary*1.15f,"Giant doodle benefits from large face on equal travel");Game.ShowBoard();}
   Game.ChooseJob(19);Game.SelectTool(1);Game.BeginWork();Game.SelectMode(ContactMode.Face);Vector2 pos=new Vector2(-2,-1.68f);Game.Controller.ProcessInput(pos,false,true,.02f);Game.Controller.ProcessInput(pos,true,true,.02f);
   for(int leg=0;leg<40;leg++){Vector2 from=pos,to=new Vector2(-2+(leg+1)*.1f,-1.5f+(leg%2==0?1:-1)*.18f);for(int part=1;part<=6;part++){pos=Vector2.Lerp(from,to,part/6f);Game.Controller.ProcessInput(pos,true,true,.024f);yield return null;}}
   Check(Game.Economy.JobLongest>=5,"Banner graphite supports a valuable natural zigzag strand");Check(Game.Paper.Drawing.Erased>0&&Game.Economy.ProducedGrams>0,"Banner strands consume actual graphite");yield return Capture("09-banner-strand");Game.CollectCrumbs();Check(Game.Economy.Inventory.Count>0,"New-job long strand can be collected");long money=Game.Economy.Wallet.Balance;long sale=Game.Economy.SellLongs();Check(sale>0&&Game.Economy.Wallet.Balance==money+sale,"New-job strand sells through unchanged economy");Game.ShowBoard();
   Game.OpenShop(true);yield return Capture("08-inventory");Game.CloseShop();Check(Game.Catalog.tools[5].price==7800,"Premium price unchanged");Application.Quit(fail==0?0:1);
  }
 }
}
