using System;
using System.Collections;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;
namespace Keshiya {
 public sealed class RuntimeExternal01Checks:MonoBehaviour {
  public PrototypeGame Game;static bool running;int count,fail;string dir;StringBuilder output=new StringBuilder();
  void Check(bool ok,string text){count++;if(!ok)fail++;output.AppendLine((ok?"PASS ":"FAIL ")+text);File.WriteAllText(Path.Combine(dir,"runtime.txt"),output+$"Checks={count}; Failures={fail}\n");}
  IEnumerator Capture(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return new WaitForSecondsRealtime(.2f);}
  void Initial(){Check(Game.Progress.wallet.Balance==0,"fixed initial money");Check(Game.Tools.items.Count==3,"three starter individuals");Check(Game.Tools.items.All(x=>x.state.UsedUnits==0&&x.state.CornerSharpness==1&&x.state.special.graphiteLoad==0&&x.state.special.toastLevel==0),"fresh wear and special states");Check(Game.Progress.levels.All(x=>x==0)&&Game.Progress.banks.All(x=>x.total==0&&x.availableSP==0&&x.earnedSP==0),"zero skills EXP SP");Check(Game.Session.CompletedCount==0&&Game.Tools.purchases.Count==0&&Game.Tools.records.All(x=>!x.purchased&&x.uses==0),"empty history collection purchases");Check(Game.ContactGuide.Enabled&&!Game.Tools.loadout.limited,"guide on unlimited carry");Check(Game.Economy.Inventory.Count==0&&Game.Economy.Ball.Grams==0,"empty crumb stock");}
  IEnumerator Start(){if(running){Destroy(gameObject);yield break;}running=true;DontDestroyOnLoad(gameObject);Application.runInBackground=true;Game.Controller.ExternalInput=true;dir=Path.Combine(Application.dataPath,"../TestResults-External01");Directory.CreateDirectory(dir);yield return new WaitForSecondsRealtime(.5f);
   Initial();Check(!Game.WorkHUD.ShowToolRecommendations,"friend details do not prescribe tools");Check(TutorialHints.Steps[4].Contains("Ctrl＋Wheel")&&!TutorialHints.Steps[4].Contains("Shift"),"tutorial teaches final Ctrl Wheel mapping");Check(Game.External.Welcome&&Game.External.ModalOpen,"development welcome visible");Check(!Game.DebugMode&&!Debug.isDebugBuild,"normal build debug disabled");Check(Game.Jobs.Count(x=>x.externalTest)==8&&Game.WorkHUD.ExternalOnly,"eight friend jobs");yield return Capture("01-welcome");
   Game.SkillsHUD.ToggleDebug();Game.ShopHUD.ToggleDebug();Game.Controller.HandleKeyDown(KeyCode.F4);Game.Controller.HandleKeyDown(KeyCode.F3);Check(!Game.SkillsHUD.DebugVisible&&!Game.ShopHUD.DebugVisible&&!Game.DebugEraseAreaVisible&&!Game.CrumbDebug,"developer actions blocked");
   Game.External.ContinueWelcome(true);Check(Game.Session.Phase==WorkPhase.Detail&&Game.Jobs[Game.Session.Selected].id=="TEST_001","recommended first job is optional detail");yield return Capture("02-detail");Game.BeginWork();Check(Game.External.ShowTutorial&&!Game.InputBlocked,"tutorial does not lock rubbing");Check(Game.External.PointerOverHint(new Vector2(420*Screen.width/1280f,Screen.height*(1-110/800f))),"hint clicks excluded from rubbing");yield return Capture("03-tutorial");
   for(int i=0;i<TutorialHints.Steps.Length;i++){Check(Game.External.Tutorial.Index==i&&!string.IsNullOrEmpty(Game.External.Tutorial.Text),"sequential hint "+i);Game.External.Tutorial.Tick(31,true);}Check(Game.External.Tutorial.Done,"tutorial completes within 217 seconds");Game.External.Tutorial.Replay();Check(Game.External.Tutorial.Index==0&&!Game.External.Tutorial.Done,"tutorial replay");Game.External.Tutorial.Skip();Check(Game.External.Tutorial.Done,"tutorial skip");
   var screen=Game.Viewport.View.pixelRect.center;Game.Viewport.HandleWheel(3,true,screen);float zoom=Game.Viewport.Zoom;var center=Game.Viewport.Center;Game.Viewport.HandleWheel(1,false,screen);Check(zoom>1&&Game.Viewport.Zoom==zoom&&Game.Viewport.Center!=center,"Ctrl Wheel zoom normal Wheel pan");Game.Viewport.ResetView();
   for(int pass=0;pass<60&&!Game.CurrentJob.CanComplete(Game.Paper);pass++){if(!Game.HasUsableTool){Game.NextTool();Game.BorrowTool();}for(float y=-Game.Paper.Size.y*.5f+.04f;y<Game.Paper.Size.y*.5f;y+=.24f){Game.Rub(new Vector2(-2.46f,y),new Vector2(2.46f,y),3);yield return null;}}
   Check(Game.CurrentJob.CanComplete(Game.Paper),"starter Lv0 tools complete TEST001");Game.Finish();Check(Game.Session.Phase==WorkPhase.Result&&Game.Progress.wallet.Balance>0,"first reward and freedom");yield return Capture("04-first-result");Game.ShowBoard();
   Game.OpenShop();Check(Game.ShopOpen,"shop available");yield return Capture("05-shop-no-debug");Game.CloseShop();Game.OpenSkills();Check(Game.SkillsOpen,"skills available");yield return Capture("06-skills-no-debug");Game.CloseSkills();
   foreach(var job in Game.Jobs.Where(x=>x.externalTest)){Game.ChooseJob(Array.IndexOf(Game.Jobs,job));Check(Game.Session.Phase==WorkPhase.Detail,"free choice "+job.id);}
   Game.ChooseJob(Array.FindIndex(Game.Jobs,x=>x.id=="TEST_002"));Game.BeginWork();Game.Assist.ToggleSample();yield return null;var nav=Game.Assist.Preview;nav.Wheel(3,true,nav.Frame.center);float z=nav.Zoom;var o=nav.Offset;nav.Wheel(1,false,nav.Frame.center);Check(z>1&&nav.Zoom==z&&nav.Offset!=o,"preview same wheel controls");yield return Capture("07-preview");Game.Assist.ToggleSample();Game.RequestRestart();Game.ConfirmRestart();Check(Game.External.Restarts==1&&Game.Paper.Drawing.Erased==0,"working restart retained");
   Game.External.OpenMenu();Check(Game.External.Menu&&Game.InputBlocked,"help blocks work");Game.External.ShowFps=true;Check(Game.External.ShowFps&&Game.External.AverageFps>0,"FPS toggle and samples");yield return Capture("08-help");Game.External.RequestDataReset();Check(Game.External.ResetConfirmation,"reset confirmation required");long balance=Game.Progress.wallet.Balance;Game.External.CancelDataReset();Check(!Game.External.ResetConfirmation&&Game.Progress.wallet.Balance==balance,"cancel global reset preserves progress");Game.External.RequestDataReset();yield return Capture("09-reset-confirmation");
   string log=Game.External.Journal.FileForTests;Check(File.Exists(log)&&Game.External.Journal.Available,"local session log exists");Debug.LogError("Synthetic C:\\Users\\PRIVATE_TEST_USER\\secret.txt 192.0.2.1");yield return null;string contents=File.ReadAllText(log);Check(contents.Contains("RuntimeError")&&!contents.Contains("PRIVATE_TEST_USER")&&!contents.Contains("192.0.2.1")&&!contents.Contains("C:\\")&&!contents.Contains("Users"),"raw errors and personal paths never logged");Check(contents.Contains("JobStarted")&&contents.Contains("JobCompleted")&&contents.Contains("JobRestarted")&&contents.Contains("ToolUsage")&&contents.Contains("modeRatios"),"job and tool analytics recorded");Check(SessionJournal.Token("C:\\Users\\name")=="redacted","token whitelist rejects paths");
   Game.External.ConfirmDataReset();yield return null;yield return new WaitForSecondsRealtime(1);Game=FindFirstObjectByType<PrototypeGame>();Game.Controller.ExternalInput=true;Initial();Check(Game.External.Welcome&&Game.External.Tutorial.Index==0,"global reset returns fresh welcome tutorial");Check(File.Exists(log),"reset preserves diagnostic history");Check(File.ReadAllText(log).Contains("DataReset")&&File.ReadAllText(log).Contains("averageFps"),"reset closes session with performance summary");yield return Capture("10-reset-fresh");Game.External.ContinueWelcome(false);Check(Game.Session.Phase==WorkPhase.Board,"free choice welcome option");Application.Quit(fail==0?0:1);
  }
 }
}
